#!/usr/bin/python2.6
"""
Usage:
    update-asgs STACK_NAME [options]

Options:
    --region=TEXT   aws region [default: eu-west-1]
"""

import logging

from docopt import docopt
from aws_updater.stack import StackUpdater

logging.basicConfig(format='%(asctime)s %(levelname)s %(message)s', datefmt='%Y-%m-%dT%H:%M:%S', level=logging.INFO)
logger = logging.getLogger(__name__)

arguments = docopt(__doc__)

stack_name = arguments["STACK_NAME"]
region = arguments["--region"]

print "update-asgs: update the asgs of a stack in a high-available manner"
print "=================================================================="

try:
    StackUpdater(stack_name, region).update_asgs()
except Exception as e:
    print "[Error] Problem while updating stack {0}: {1}".format(stack_name, e)
    raise
